import React from 'react';
import { FaRobot, FaLightbulb, FaExclamationTriangle } from 'react-icons/fa';

const insights = [
    {
        type: 'positive',
        text: 'Citizen engagement in Education department has increased by 18% compared to the previous quarter, supporting strong policy adoption across Tier-1 cities.'
    },
    {
        type: 'warning',
        text: 'Healthcare approval rate dipped below 92.4% threshold. Recommend reviewing the pending scheme applications (Pile #Feb 17) for potential process bottleneck.'
    },
    {
        type: 'positive',
        text: 'AI workflow automation is now operational — including Tax S2012 — and is processing over 1.3M citizen queries per day at 94.7% resolution accuracy.'
    }
];

const AiPerformanceInsightsWidget = () => {
    return (
        <div className="bg-gradient-to-br from-[#0052cc] via-[#1d4ed8] to-[#1e3a8a] text-white rounded-2xl p-5 shadow-md space-y-4 select-none text-left">
            {/* Header */}
            <div className="flex items-center gap-2.5">
                <div className="w-8 h-8 rounded-xl bg-white/15 flex items-center justify-center shrink-0">
                    <FaRobot className="w-4 h-4 text-white" />
                </div>
                <div>
                    <h3 className="text-sm font-extrabold text-white">AI Performance Insights</h3>
                    <p className="text-[10px] text-blue-200 font-medium">Generated by PolicyGPT Intelligence</p>
                </div>
            </div>

            {/* Insights List */}
            <div className="space-y-3">
                {insights.map((ins, i) => (
                    <div key={i} className="bg-white/10 border border-white/15 rounded-xl p-3 space-y-1.5">
                        <div className="flex items-center gap-1.5">
                            {ins.type === 'positive' ? (
                                <FaLightbulb className="w-3 h-3 text-amber-300 shrink-0" />
                            ) : (
                                <FaExclamationTriangle className="w-3 h-3 text-rose-300 shrink-0" />
                            )}
                            <span className={`text-[9px] font-black uppercase tracking-wider ${ins.type === 'positive' ? 'text-emerald-300' : 'text-rose-300'}`}>
                                {ins.type === 'positive' ? 'Insight' : 'Alert'}
                            </span>
                        </div>
                        <p className="text-[11px] text-blue-50 font-medium leading-relaxed">{ins.text}</p>
                    </div>
                ))}
            </div>
        </div>
    );
};

export default AiPerformanceInsightsWidget;
