import React from 'react';
import { FaDownload, FaArrowRight } from 'react-icons/fa';

const RecentReportsTable = ({ onViewAll, onDownloadReport }) => {
    const reports = [
        {
            id: 1,
            name: "Q3 Housing Policy Compliance",
            meta: "Generated Oct 12, 2024 • PDF",
            department: "Urban Dev.",
            author: "S. Chen",
            avatarBg: "bg-blue-100 text-[#0052cc]",
            status: "Complete",
            statusType: "success"
        },
        {
            id: 2,
            name: "Citizen Eligibility Trends 2024",
            meta: "Generated Oct 12, 2024 • CSV",
            department: "Welfare Admin",
            author: "J. Doe",
            avatarBg: "bg-sky-100 text-sky-700",
            status: "Complete",
            statusType: "success"
        },
        {
            id: 3,
            name: "AI Data Privacy Impact Audit",
            meta: "Generated Oct 11, 2024 • PDF",
            department: "Min. of IT",
            author: "A. Russo",
            avatarBg: "bg-purple-100 text-purple-700",
            status: "Processing",
            statusType: "processing"
        }
    ];

    return (
        <div className="bg-white border border-slate-200 rounded-2xl p-5 shadow-sm select-none text-left space-y-4">
            {/* Table Header */}
            <div className="flex items-center justify-between">
                <h3 className="text-base font-extrabold text-slate-900 tracking-tight">
                    Recent Reports
                </h3>
                <button
                    onClick={onViewAll}
                    className="text-xs font-bold text-[#0052cc] hover:underline flex items-center gap-1 cursor-pointer"
                >
                    <span>View All</span>
                    <FaArrowRight className="w-2.5 h-2.5" />
                </button>
            </div>

            {/* Table View */}
            <div className="overflow-x-auto">
                <table className="w-full text-left border-collapse">
                    <thead>
                        <tr className="border-b border-slate-200/80 text-[10px] font-black text-slate-400 uppercase tracking-wider">
                            <th className="py-2.5 px-3">Report Name</th>
                            <th className="py-2.5 px-3">Department</th>
                            <th className="py-2.5 px-3">Generated By</th>
                            <th className="py-2.5 px-3 text-right">Status</th>
                        </tr>
                    </thead>
                    <tbody className="divide-y divide-slate-100 text-xs">
                        {reports.map((report) => (
                            <tr key={report.id} className="hover:bg-slate-50/70 transition-colors group">
                                {/* Report Name & Subtext */}
                                <td className="py-3 px-3">
                                    <div className="space-y-0.5">
                                        <div className="font-extrabold text-slate-900 group-hover:text-[#0052cc] transition-colors">
                                            {report.name}
                                        </div>
                                        <div className="text-[11px] font-medium text-slate-400">
                                            {report.meta}
                                        </div>
                                    </div>
                                </td>

                                {/* Department */}
                                <td className="py-3 px-3 font-semibold text-slate-700">
                                    {report.department}
                                </td>

                                {/* Generated By Author */}
                                <td className="py-3 px-3">
                                    <div className="flex items-center gap-2">
                                        <div className={`w-6 h-6 rounded-full ${report.avatarBg} text-[10px] font-black flex items-center justify-center shrink-0`}>
                                            {report.author.split(' ').map(n => n[0]).join('')}
                                        </div>
                                        <span className="font-bold text-slate-800">{report.author}</span>
                                    </div>
                                </td>

                                {/* Status Badge */}
                                <td className="py-3 px-3 text-right">
                                    <div className="flex items-center justify-end gap-2">
                                        {report.statusType === 'success' ? (
                                            <span className="inline-flex items-center gap-1.5 px-2.5 py-0.5 bg-emerald-50 text-emerald-600 border border-emerald-200 rounded-full text-[10px] font-bold">
                                                <span className="w-1.5 h-1.5 rounded-full bg-emerald-500" />
                                                {report.status}
                                            </span>
                                        ) : (
                                            <span className="inline-flex items-center gap-1.5 px-2.5 py-0.5 bg-blue-50 text-[#0052cc] border border-blue-200 rounded-full text-[10px] font-bold">
                                                <span className="w-1.5 h-1.5 rounded-full bg-[#0052cc] animate-pulse" />
                                                {report.status}
                                            </span>
                                        )}

                                        {report.statusType === 'success' && (
                                            <button
                                                onClick={() => onDownloadReport(report)}
                                                title="Download Report"
                                                className="p-1.5 text-slate-400 hover:text-[#0052cc] hover:bg-blue-50 rounded-lg transition-colors cursor-pointer"
                                            >
                                                <FaDownload className="w-3 h-3" />
                                            </button>
                                        )}
                                    </div>
                                </td>
                            </tr>
                        ))}
                    </tbody>
                </table>
            </div>
        </div>
    );
};

export default RecentReportsTable;
